version: "3.9"

services:
  backend-test:
    build: 
      context: ./backend
      dockerfile: Dockerfile
    command: ["yarn", "test"]
    env_file:
      - ./env/test.env
    ports: 
      - "8000"
    networks: 
      - url-shortener-test
  
  frontend-test:
    build: 
      context: ./web
      dockerfile: Dockerfile
    command: ["yarn", "test", "--watchAll=false"]
    env_file:
      - ./env/test.env
    networks: 
      - url-shortener-test

networks: 
  url-shortener-test: {}
